### ISSUE TITLE
Could not bring up existing saved search via dropdown

### ISSUE THREAD

**Issue by davehannon** [flexion/hud-disaster-data#6]
An outside user hit the dev site with a Chromebook, and was not able to retrieve a saved search from the dropdown.  

He could recreated it with the following steps:

- create a list of disasters into the current extract 
- save the list
- do a clear (so it empties the current extract)
- click on the drop down
- click on the saved search name

It gave the following on the console:

Uncaught TypeError: Cannot read property 'disasters' of undefined
    at loadExtract (https://hud-disaster-data-dev.app.cloud.gov/static/js/app.44f527ba5a0b9a385c0c.js:1:1161)
    at https://hud-disaster-data-dev.app.cloud.gov/static/js/vendor.fb12822859b9e9246aeb.js:1:4553
    at https://hud-disaster-data-dev.app.cloud.gov/static/js/vendor.fb12822859b9e9246aeb.js:6:3378
    at Array.forEach (native)
    at https://hud-disaster-data-dev.app.cloud.gov/static/js/vendor.fb12822859b9e9246aeb.js:6:3358
    at T._withCommit (https://hud-disaster-data-dev.app.cloud.gov/static/js/vendor.fb12822859b9e9246aeb.js:6:4870)
    at T.commit (https://hud-disaster-data-dev.app.cloud.gov/static/js/vendor.fb12822859b9e9246aeb.js:6:3333)
    at T.commit (https://hud-disaster-data-dev.app.cloud.gov/static/js/vendor.fb12822859b9e9246aeb.js:6:2852)
    at u.loadExtract (https://hud-disaster-data-dev.app.cloud.gov/static/js/app.44f527ba5a0b9a385c0c.js:1:5231)
    at n (https://hud-disaster-data-dev.app.cloud.gov/static/js/vendor.fb12822859b9e9246aeb.js:11:942)

**Comment by pjoice** [comment]
Uhhh... what? Is this "outside user" part of our team or are you saying a random person used the app and submitted feedback?

**Comment by davehannon** [comment]
Sorry, I worded that a little strangely.  It was my business partner Mike, who had asked about how the project was going.  I showed him the dev site, and he had the problem I described.  So, he's not really "outside", just not directly on our team.

**Comment by davehannon** [comment]
Obsolete issue
